services:
  unbound:
    container_name: unbound
    build:
      context: ./unbound

    expose:
      - "5335/tcp"
      - "5335/udp"

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "dig @127.0.0.1 -p 5335 . NS +time=2 +tries=1 +short | grep -q 'root-servers.net'"
        ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest

    depends_on:
      unbound:
        condition: service_healthy

    ports:
      # DNS
      - "53:53/tcp"
      - "53:53/udp"

      # Webinterface
      - "8080:80/tcp"
      - "8443:443/tcp"

    environment:
      TZ: "Europe/Amsterdam"
      FTLCONF_webserver_api_password: "${PIHOLE_PASSWORD}"
      FTLCONF_dns_listeningMode: "ALL"
      FTLCONF_dns_upstreams: "unbound#5335"
      FTLCONF_dns_hosts: |-
        192.168.2.37 Cornelia cornelia.lan

    volumes:
      - "./etc-pihole:/etc/pihole"

    restart: unless-stopped
